version: '3.8'

services:
  app:
    build: .
    container_name: api-server
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - "${API_PORT}:${CONTAINER_API_PORT}"
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_CLIENT: ${DB_CLIENT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - db
    command: >
      sh -c "
      yarn install &&
      yarn start
      "

  db:
    image: postgres:alpine
    container_name: api-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${CONTAINER_DB_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
